[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "evaspa"
dynamic = ["version"]
description = "Python implementation of EVASPA algorithm"
readme = "README.md"
requires-python = ">=3.10"
license = "LicenseRef-Public-Domain"
keywords = []
authors = [
  { name = "Emmanuelle Sarrazin", email = "emmanuelle.sarrazin@cnes.fr" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "geopandas",
  "numpy",
  "pandas",
  "scipy",
  "xarray",
  "rasterio",
  "scikit-image",
  "shapely",
  "sensorsio",
  "pydantic>=2.8",
  "timezonefinder",
  "pwlf",
]

[project.optional-dependencies]
dev = [
  "hatch",
  "pytest",
  "pre-commit",
]
notebook = [
  "matplotlib",
  "jupyterlab",
  "notebook",
  "contextily",
]
docs = [
  "mkdocs",
  "mkdocstrings[python]",
  "mkdocs-material",
  "mkdocs-gen-files",
  "mkdocs-autorefs",
  "mkdocs-literate-nav",
  "mkdocs-jupyter",
]

[project.urls]
Source = "https://gitlab.cnes.fr/cesbio/evaspa"

[project.scripts]
evaspa = "evaspa.cli:evaspa"
evaspa-tiling = "evaspa.cli:evaspa_tiling"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/evaspa"]

[tool.hatch.version]
path = "src/evaspa/__about__.py"

[tool.hatch.envs.hatch-static-analysis]
config-path = "none"
dependencies = ["ruff==0.8.4"]

[tool.hatch.envs.hatch-test]
default-args = ["tests"]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
[tool.hatch.envs.hatch-test.scripts]
run = "pytest{env:HATCH_TEST_ARGS:} {args}"
run-cov = "coverage run -m pytest{env:HATCH_TEST_ARGS:} {args}"
cov-combine = "coverage combine"
cov-report = "coverage report"

[tool.pytest.ini_options]
markers = [
    "requires_test_data: Require additional test data. Use environment variables EVASPA_TEST_DATA_PATH.",
]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.10", "3.11", "3.12"]

[tool.hatch.envs.types]
dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/evaspa tests}"

[tool.coverage.run]
source_pkgs = ["evaspa", "tests"]
branch = true
parallel = true
omit = [
  "src/evaspa/__about__.py",
]

[tool.coverage.paths]
evaspa = ["src/evaspa", "*/evaspa/src/evaspa"]
tests = ["tests", "*/evaspa/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.mypy]
exclude = []
plugins = ["numpy.typing.mypy_plugin"]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = [
    "affine",
    "click",
    "geopandas",
    "fiona.*",
    "matplotlib.*",
    "scipy.*",
    "pytest",
    "rasterio.*",
    "sensorsio.*",
    "shapely.*",
    "pwlf.*",
    "mkdocs_gen_files.*",
]
ignore_missing_imports = true

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64","win-64"]

[tool.pixi.pypi-dependencies]
evaspa = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
notebook = { features = ["notebook"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.12.*"
pip = ">=24.3.1,<25"
gdal = ">=3.10.0,<4"
hdf4 = ">=4.2.15,<5"
hdf5 = ">=1.14.4,<2"
netcdf4 = ">=1.7.2,<2"
h5netcdf = ">=1.4.1,<2"
