[project]
name = "sweat"
description = "Spatial Waterstress and Evapotranspiration Assessment for TRISHNA: Python implementation of EVASPA, STIC and ET timeseries algorithms"
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.12"
license = "LicenseRef-Public-Domain"
keywords = []
authors = [
  { name = "Emmanuelle Sarrazin", email = "emmanuelle.sarrazin@cnes.fr" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "geopandas",
  "numpy<2.3",
  "pandas",
  "scipy<1.18",
  "xarray",
  "rasterio",
  "scikit-image",
  "shapely",
  "sensorsio",
  "pydantic>=2.8",
  "timezonefinder",
  "pwlf",
  "numba",
  "rioxarray",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "pre-commit",
  "pip-review",
  "nbformat",
  "nbconvert",
  "ruff",
  "mypy",
]
notebook = [
  "matplotlib",
  "jupyterlab",
  "notebook",
  "contextily",
]
docs = [
  "mkdocs",
  "mkdocstrings[python]",
  "mkdocs-material",
  "mkdocs-gen-files",
  "mkdocs-autorefs",
  "mkdocs-literate-nav",
  "mkdocs-jupyter",
]

[project.urls]
Source = "https://src.koda.cnrs.fr/trishna/sweat"

[project.scripts]
evaspa = "sweat.cli:evaspa"
evaspa-tiling = "sweat.cli:evaspa_tiling"
stic = "sweat.cli:stic"
timeseries = "sweat.cli:timeseries"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = ["-m", "not skip or not slow"]
markers = [
    "unit: mark a test as a unit test.",
    "functional: mark a test a functional test.",
    "end_to_end: mark a test as an end-to-end test.",
    "notebooks: mark a test that runs notebooks.",
    "slow: mark a test that is slow to run.",
    "docs: mark a test for docs.",
    "skip: mark a test that must be skipped.",
    "require_test_data: mark a test that requires EVASPA_TEST_DATA_PATH environment variable to be set to the test dataset folder",
]
filterwarnings = [
    "ignore::DeprecationWarning:jupyter_client",
]
testpaths=["tests"]

[tool.coverage.run]
source = ["sweat","tests"]
branch = true
parallel = true
omit = [
  "src/sweat/__about__.py",
  "./.pixi/*",
  "./hooks/*",
]

[tool.coverage.paths]
sweat = ["src/sweat"]
tests = ["tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.mypy]
exclude = []
plugins = ["numpy.typing.mypy_plugin"]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = [
    "affine",
    "click",
    "geopandas",
    "fiona.*",
    "matplotlib.*",
    "scipy.*",
    "pytest",
    "rasterio.*",
    "sensorsio.*",
    "shapely.*",
    "pwlf.*",
    "mkdocs_gen_files.*",
    "nbformat",
    "nbconvert.*",
    "numba",
]
ignore_missing_imports = true

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64","win-64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
sweat = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev","notebook","docs"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.12.*"
pip = ">=24.3.1,<25"
gdal = ">=3.10.0,<4"
hdf4 = ">=4.2.15,<5"
hdf5 = ">=1.14.4,<2"
netcdf4 = ">=1.7.2,<2"
h5netcdf = ">=1.4.1,<2"
numpy = ">=2.2,<2.3"
matplotlib = ">=3.10.7,<4"
